### PR TITLE
sensor/vl53l1x update to version 2.4.5

### PR DESCRIPTION
**Pull request by FRASTM**
This library written by STMicroelectronics is dedicated to vl53l1x time of flight sensor. This library is called from the vl53l1x driver and is kept transparent for user. User is calling a standard Zephyr driver and then the driver makes some calls to this library.

Origin: ST Microelectronics
License: BSD-3-Clause
URL: http://www.st.com/en/embedded-software/stsw-img007.html
Commit: v2.4.5
Purpose: ST Microelectonics official API to use vl53l1x sensor.
Maintained-by: External

### CODE REVIEW

**Comment by FRASTM** [comment]
Add a commit to change the function call to VL53L1_GetTickCount   
See [vl53l1_platform.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1_platform.h)

**Comment by MaureenHelm** [comment]
Is there a zephyr-side PR that pulls this into the west manifest?

**Comment by FRASTM** [comment]
> Is there a zephyr-side PR that pulls this into the west manifest?

see https://github.com/zephyrproject-rtos/zephyr/pull/61421

**Review by erwango — CHANGES_REQUESTED** [review]
Can we try to get minimized git diff ?
If this is a file rights, or dos2unix issue, make a commit on the initial files first and then apply the new version.
Currently this 100% difference status makes it impossible to review.

**Comment by FRASTM** [comment]
> Can we try to get minimized git diff ? If this is a file rights, or dos2unix issue, make a commit on the initial files first and then apply the new version. Currently this 100% difference status makes it impossible to review.

done in new commit a610deeafdec1f2adfee25198cfd3dc746b34dcf

**Comment by erwango** [comment]
> done in new commit https://github.com/zephyrproject-rtos/hal_st/commit/a610deeafdec1f2adfee25198cfd3dc746b34dcf

Now we have 2 commits with 100% difference:
- Commit 1: V1.0 (Unix) vs V1.1 (DOS)
- Commit 2: V1.1 (DOS) vs V1.1 (Unix)

Aim is to have set of files with same formatting when applying the new version, hence:
- V1.0 (Unix) vs V1.1 (Unix)  > Should make the exact diff appear
So you should convert V1.1 from DOS to Unix out of tree before applying the channge.

Note that I don't know exactly if the issue comes from dos2unix formatting. It can come from another formatting difference.

**Review by avisconti — APPROVED** [review]
LGTM, thx

**Review by erwango — APPROVED** [review]

**Pull request merged**
